spring.datasource.url=jdbc:postgresql://localhost:5432/codepathwaydb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.write-dates-as-timestamps=false
server.port=8080
app.jwt.secret=codepathwaysecret1234567890
app.jwt.expiration-ms=86400000
